<?php

namespace Database\Seeders;

use App\Models\Candidate;
use App\Models\QuickCountParty;
use App\Models\QuickCountTps;
use Illuminate\Database\Seeder;

class QuickCountAndCandidateSeeder extends Seeder
{
    public function run(): void
    {
        // =========================================================================
        // 1. QUICK COUNT PARTIES (Hasil Rekapitulasi Suara Partai Politik Banyumas)
        // =========================================================================
        QuickCountParty::query()->delete();

        $parties = [
            [
                'party_name' => 'PDI Perjuangan',
                'party_number' => 3,
                'color_hex' => '#dc2626',
                'total_suara' => 195420,
                'kursi_dprd' => 17,
            ],
            [
                'party_name' => 'Partai Kebangkitan Bangsa (PKB)',
                'party_number' => 1,
                'color_hex' => '#059669',
                'total_suara' => 118740,
                'kursi_dprd' => 9,
            ],
            [
                'party_name' => 'Partai Gerakan Indonesia Raya (Gerindra)',
                'party_number' => 2,
                'color_hex' => '#ea580c',
                'total_suara' => 98650,
                'kursi_dprd' => 7,
            ],
            [
                'party_name' => 'Partai Golongan Karya (Golkar)',
                'party_number' => 4,
                'color_hex' => '#f59e0b',
                'total_suara' => 79430,
                'kursi_dprd' => 5,
            ],
            [
                'party_name' => 'Partai NasDem',
                'party_number' => 5,
                'color_hex' => '#001333',
                'total_suara' => 74850,
                'kursi_dprd' => 6,
            ],
            [
                'party_name' => 'Partai Keadilan Sejahtera (PKS)',
                'party_number' => 8,
                'color_hex' => '#f97316',
                'total_suara' => 64210,
                'kursi_dprd' => 4,
            ],
            [
                'party_name' => 'Partai Demokrat',
                'party_number' => 14,
                'color_hex' => '#2563eb',
                'total_suara' => 32180,
                'kursi_dprd' => 1,
            ],
            [
                'party_name' => 'Partai Amanat Nasional (PAN)',
                'party_number' => 12,
                'color_hex' => '#0284c7',
                'total_suara' => 28540,
                'kursi_dprd' => 1,
            ],
            [
                'party_name' => 'Partai Persatuan Pembangunan (PPP)',
                'party_number' => 17,
                'color_hex' => '#16a34a',
                'total_suara' => 16320,
                'kursi_dprd' => 0,
            ],
            [
                'party_name' => 'Partai Solidaritas Indonesia (PSI)',
                'party_number' => 15,
                'color_hex' => '#e11d48',
                'total_suara' => 8910,
                'kursi_dprd' => 0,
            ],
        ];

        foreach ($parties as $p) {
            QuickCountParty::create($p);
        }

        // =========================================================================
        // 2. CALON LEGISLATIF (50 Caleg DPRD Kabupaten Banyumas Periode 2024 - 2029)
        // =========================================================================
        Candidate::query()->delete();

        $candidates = [
            // DAPIL 1 (Alokasi 8 Kursi - Purwokerto Barat, Purwokerto Timur, Purwokerto Selatan, Purwokerto Utara, Patikraja)
            [
                'nama' => 'Dr. H. Edris Santoso, S.E., M.M.',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 1',
                'nomor_urut' => 1,
                'jenis_kelamin' => 'L',
                'foto' => '/images/ketua_dpd.jpg',
                'jabatan' => 'Ketua DPD Partai NasDem Banyumas',
                'basis_wilayah' => 'Purwokerto Barat & Purwokerto Selatan',
                'target_suara' => 12000,
                'suara_masuk' => 11480,
                'status' => 'Caleg Terpilih',
                'slogan' => 'Mengabdi Tanpa Henti untuk Restorasi Banyumas',
                'phone' => '0813-2764-2853',
                'pendidikan_terakhir' => 'S3 Ilmu Manajemen',
            ],
            [
                'nama' => 'Rina Wahyuni, S.H.',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 1',
                'nomor_urut' => 2,
                'jenis_kelamin' => 'P',
                'foto' => null,
                'jabatan' => 'Wakil Bendahara DPD / Advokat',
                'basis_wilayah' => 'Purwokerto Timur & Purwokerto Utara',
                'target_suara' => 6500,
                'suara_masuk' => 4820,
                'status' => 'DCT',
                'slogan' => 'Hukum Berkeadilan, Perempuan Berdaya',
                'phone' => '0812-4455-6677',
                'pendidikan_terakhir' => 'S1 Ilmu Hukum',
            ],
            [
                'nama' => 'Bayu Wicaksono, S.T.',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 1',
                'nomor_urut' => 3,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Ketua DPC Purwokerto Barat / Arsitek',
                'basis_wilayah' => 'Purwokerto Barat',
                'target_suara' => 7000,
                'suara_masuk' => 5410,
                'status' => 'DCT',
                'slogan' => 'Tata Ruang Maju untuk Warga Sejahtera',
                'phone' => '0857-1122-8899',
                'pendidikan_terakhir' => 'S1 Teknik Arsitektur',
            ],
            [
                'nama' => 'Dra. Endang Kusuma Dewi, M.Pd.',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 1',
                'nomor_urut' => 4,
                'jenis_kelamin' => 'P',
                'foto' => null,
                'jabatan' => 'Tokoh Pendidikan / Purnawirawan Guru',
                'basis_wilayah' => 'Purwokerto Utara & Patikraja',
                'target_suara' => 5500,
                'suara_masuk' => 3950,
                'status' => 'DCT',
                'slogan' => 'Pendidikan Berkualitas untuk Generasi Unggul',
                'phone' => '0818-9988-7766',
                'pendidikan_terakhir' => 'S2 Manajemen Pendidikan',
            ],
            [
                'nama' => 'Andrianto',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 1',
                'nomor_urut' => 5,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Wakil Ketua Bidang Penggalangan Komunitas',
                'basis_wilayah' => 'Patikraja & Purwokerto Selatan',
                'target_suara' => 5000,
                'suara_masuk' => 3240,
                'status' => 'DCT',
                'slogan' => 'Solid Bersama Komunitas Rakyat',
                'phone' => '0821-3344-5566',
                'pendidikan_terakhir' => 'SMA / Sederajat',
            ],
            [
                'nama' => 'Bagus Panuntun Hutama Putra',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 1',
                'nomor_urut' => 6,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Wakil Ketua Bidang Pemilih Pemula & Milenial',
                'basis_wilayah' => 'Purwokerto Timur',
                'target_suara' => 4500,
                'suara_masuk' => 3120,
                'status' => 'DCT',
                'slogan' => 'Suara Milenial Menuju Gerakan Perubahan',
                'phone' => '0896-1234-5678',
                'pendidikan_terakhir' => 'S1 Ilmu Komunikasi',
            ],
            [
                'nama' => 'Tri Astuti, S.E.',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 1',
                'nomor_urut' => 7,
                'jenis_kelamin' => 'P',
                'foto' => null,
                'jabatan' => 'Aktivis UMKM & Pemberdayaan Ekonomi',
                'basis_wilayah' => 'Purwokerto Selatan',
                'target_suara' => 4000,
                'suara_masuk' => 2890,
                'status' => 'DCT',
                'slogan' => 'UMKM Naik Kelas, Ekonomi Keluarga Kuat',
                'phone' => '0877-6543-2109',
                'pendidikan_terakhir' => 'S1 Ekonomi Pembangunan',
            ],
            [
                'nama' => 'Suryo Wibowo, S.H.',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 1',
                'nomor_urut' => 8,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Praktisi Hukum & Bantuan Hukum Masyarakat',
                'basis_wilayah' => 'Patikraja',
                'target_suara' => 4000,
                'suara_masuk' => 2450,
                'status' => 'DCT',
                'slogan' => 'Keadilan untuk Semua Lapisan Warga',
                'phone' => '0813-7890-1234',
                'pendidikan_terakhir' => 'S1 Hukum',
            ],

            // DAPIL 2 (Alokasi 9 Kursi - Sokaraja, Kembaran, Sumbang, Baturraden)
            [
                'nama' => 'H. Muhlasin, S.Sos.',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 2',
                'nomor_urut' => 1,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Ketua DPC Sokaraja / Tokoh Masyarakat',
                'basis_wilayah' => 'Sokaraja & Kembaran',
                'target_suara' => 11000,
                'suara_masuk' => 10240,
                'status' => 'Caleg Terpilih',
                'slogan' => 'Amanah Memperjuangkan Hak Rakyat Sokaraja',
                'phone' => '0812-3322-1100',
                'pendidikan_terakhir' => 'S1 Sosiologi',
            ],
            [
                'nama' => 'Ani Pujianti, S.M.',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 2',
                'nomor_urut' => 2,
                'jenis_kelamin' => 'P',
                'foto' => null,
                'jabatan' => 'Wakil Ketua Bidang Tenaga Kerja DPD',
                'basis_wilayah' => 'Sumbang & Kembaran',
                'target_suara' => 7500,
                'suara_masuk' => 5980,
                'status' => 'DCT',
                'slogan' => 'Perlindungan Nyata Tenaga Kerja Banyumas',
                'phone' => '0815-6677-8899',
                'pendidikan_terakhir' => 'S1 Manajemen Bisnis',
            ],
            [
                'nama' => 'Anas Mahfudz',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 2',
                'nomor_urut' => 3,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Ketua DPC Kembaran',
                'basis_wilayah' => 'Kembaran',
                'target_suara' => 6000,
                'suara_masuk' => 4310,
                'status' => 'DCT',
                'slogan' => 'Bersatu Membangun Kembaran Lebih Maju',
                'phone' => '0822-4455-6611',
                'pendidikan_terakhir' => 'D3 Manajemen',
            ],
            [
                'nama' => 'H. Sunaryo',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 2',
                'nomor_urut' => 4,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Ketua DPC Sumbang',
                'basis_wilayah' => 'Sumbang',
                'target_suara' => 6500,
                'suara_masuk' => 4750,
                'status' => 'DCT',
                'slogan' => 'Pembangunan Desa Merata di Lereng Slamet',
                'phone' => '0813-9988-1122',
                'pendidikan_terakhir' => 'SMA / Sederajat',
            ],
            [
                'nama' => 'Wahyudi Santoso',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 2',
                'nomor_urut' => 5,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Ketua DPC Baturraden',
                'basis_wilayah' => 'Baturraden',
                'target_suara' => 5000,
                'suara_masuk' => 3820,
                'status' => 'DCT',
                'slogan' => 'Pariwisata Berkelanjutan Baturraden',
                'phone' => '0852-1234-7890',
                'pendidikan_terakhir' => 'S1 Pariwisata',
            ],
            [
                'nama' => 'Siti Nurtoyibah',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 2',
                'nomor_urut' => 6,
                'jenis_kelamin' => 'P',
                'foto' => null,
                'jabatan' => 'Pengurus DPD NasDem / Tokoh Aisyiyah',
                'basis_wilayah' => 'Sokaraja',
                'target_suara' => 4500,
                'suara_masuk' => 3120,
                'status' => 'DCT',
                'slogan' => 'Kesejahteraan Ibu dan Anak Prioritas Utama',
                'phone' => '0819-3322-5544',
                'pendidikan_terakhir' => 'S1 Tarbiyah',
            ],
            [
                'nama' => 'Iwan Yulianto, S.T.',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 2',
                'nomor_urut' => 7,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Wakil Ketua Bidang Pemuda & Olahraga',
                'basis_wilayah' => 'Sumbang & Sokaraja',
                'target_suara' => 4000,
                'suara_masuk' => 2750,
                'status' => 'DCT',
                'slogan' => 'Fasilitas Olahraga & Kepemudaan di Tiap Desa',
                'phone' => '0812-8877-6655',
                'pendidikan_terakhir' => 'S1 Teknik Sipil',
            ],
            [
                'nama' => 'Desi Nur Sekardinah',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 2',
                'nomor_urut' => 8,
                'jenis_kelamin' => 'P',
                'foto' => null,
                'jabatan' => 'Wakil Sekretaris Bidang Kebijakan Publik',
                'basis_wilayah' => 'Baturraden & Kembaran',
                'target_suara' => 3500,
                'suara_masuk' => 2410,
                'status' => 'DCT',
                'slogan' => 'Transparansi Kebijakan Demi Kesejahteraan Warga',
                'phone' => '0878-1122-3344',
                'pendidikan_terakhir' => 'S1 Ilmu Administrasi Negara',
            ],
            [
                'nama' => 'Ristam',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 2',
                'nomor_urut' => 9,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Wakil Ketua Bidang Ekonomi DPD',
                'basis_wilayah' => 'Kembaran',
                'target_suara' => 3000,
                'suara_masuk' => 2050,
                'status' => 'DCT',
                'slogan' => 'Pertumbuhan Usaha Mikro dan Koperasi Desa',
                'phone' => '0813-5566-7788',
                'pendidikan_terakhir' => 'SMA / Sederajat',
            ],

            // DAPIL 3 (Alokasi 9 Kursi - Sumpiuh, Tambak, Kemranjen, Banyumas, Somagede, Kalibagor)
            [
                'nama' => 'Drs. Supardi, M.Pd.',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 3',
                'nomor_urut' => 1,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Ketua DPC Kemranjen / Purnawirawan Pendidik',
                'basis_wilayah' => 'Kemranjen & Sumpiuh',
                'target_suara' => 10500,
                'suara_masuk' => 9870,
                'status' => 'Caleg Terpilih',
                'slogan' => 'Pengabdian Tulus untuk Banyumas Bagian Selatan',
                'phone' => '0812-2233-4455',
                'pendidikan_terakhir' => 'S2 Administrasi Pendidikan',
            ],
            [
                'nama' => 'Eni Kusrini, S.Pd.',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 3',
                'nomor_urut' => 2,
                'jenis_kelamin' => 'P',
                'foto' => null,
                'jabatan' => 'Wakil Bendahara DPD / Tokoh Pendidik',
                'basis_wilayah' => 'Tambak & Sumpiuh',
                'target_suara' => 6000,
                'suara_masuk' => 4520,
                'status' => 'DCT',
                'slogan' => 'Guru Sejahtera, Anak Bangsa Berprestasi',
                'phone' => '0856-7788-9900',
                'pendidikan_terakhir' => 'S1 Kependidikan',
            ],
            [
                'nama' => 'H. Suwarto',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 3',
                'nomor_urut' => 3,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Ketua DPC Sumpiuh / Pengusaha Penggilingan Padi',
                'basis_wilayah' => 'Sumpiuh',
                'target_suara' => 6500,
                'suara_masuk' => 4890,
                'status' => 'DCT',
                'slogan' => 'Kedaulatan Pangan & Kesejahteraan Petani',
                'phone' => '0813-1122-3344',
                'pendidikan_terakhir' => 'SMA / Sederajat',
            ],
            [
                'nama' => 'Ahmad Mudasir',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 3',
                'nomor_urut' => 4,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Ketua DPC Tambak',
                'basis_wilayah' => 'Tambak',
                'target_suara' => 5000,
                'suara_masuk' => 3640,
                'status' => 'DCT',
                'slogan' => 'Maju Bersama Petani dan Pedagang Pasar',
                'phone' => '0821-9988-7766',
                'pendidikan_terakhir' => 'SMA / Sederajat',
            ],
            [
                'nama' => 'Suryo Atmojo',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 3',
                'nomor_urut' => 5,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Ketua DPC Banyumas',
                'basis_wilayah' => 'Banyumas (Kecamatan Kota Lama)',
                'target_suara' => 5500,
                'suara_masuk' => 3910,
                'status' => 'DCT',
                'slogan' => 'Melestarikan Budaya dan Wisata Sejarah Banyumas',
                'phone' => '0857-4433-2211',
                'pendidikan_terakhir' => 'S1 Sejarah Kebudayaan',
            ],
            [
                'nama' => 'Rinawati',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 3',
                'nomor_urut' => 6,
                'jenis_kelamin' => 'P',
                'foto' => null,
                'jabatan' => 'Wakil Ketua Bidang Perempuan & Anak',
                'basis_wilayah' => 'Kalibagor & Somagede',
                'target_suara' => 4500,
                'suara_masuk' => 3150,
                'status' => 'DCT',
                'slogan' => 'Stop Kekerasan pada Anak dan Perempuan',
                'phone' => '0812-7766-5544',
                'pendidikan_terakhir' => 'S1 Psikologi',
            ],
            [
                'nama' => 'Edi Gunawan',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 3',
                'nomor_urut' => 7,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Ketua DPC Kalibagor',
                'basis_wilayah' => 'Kalibagor',
                'target_suara' => 4000,
                'suara_masuk' => 2820,
                'status' => 'DCT',
                'slogan' => 'Akses Air Bersih dan Irigasi Pertanian Mantap',
                'phone' => '0818-4455-6677',
                'pendidikan_terakhir' => 'SMA / Sederajat',
            ],
            [
                'nama' => 'Siti Maemunah, S.Ag.',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 3',
                'nomor_urut' => 8,
                'jenis_kelamin' => 'P',
                'foto' => null,
                'jabatan' => 'Pengurus Fatayat / Pendidik Madrasah',
                'basis_wilayah' => 'Somagede & Kemranjen',
                'target_suara' => 4000,
                'suara_masuk' => 2640,
                'status' => 'DCT',
                'slogan' => 'Bantuan Nyata untuk Pesantren dan Majelis Taklim',
                'phone' => '0877-3322-1144',
                'pendidikan_terakhir' => 'S1 Agama Islam',
            ],
            [
                'nama' => 'Parsono',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 3',
                'nomor_urut' => 9,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Ketua DPC Somagede',
                'basis_wilayah' => 'Somagede',
                'target_suara' => 3500,
                'suara_masuk' => 2180,
                'status' => 'DCT',
                'slogan' => 'Pemberdayaan Warga Desa Pinggiran',
                'phone' => '0823-1122-3344',
                'pendidikan_terakhir' => 'SMA / Sederajat',
            ],

            // DAPIL 4 (Alokasi 8 Kursi - Wangon, Jatilawang, Rawalo, Kebasen)
            [
                'nama' => 'Drs. H. Mahrus, M.Si.',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 4',
                'nomor_urut' => 1,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Ketua DPC Wangon / Tokoh Ulama',
                'basis_wilayah' => 'Wangon & Jatilawang',
                'target_suara' => 11000,
                'suara_masuk' => 10120,
                'status' => 'Caleg Terpilih',
                'slogan' => 'Religius, Merakyat, Berintegritas',
                'phone' => '0812-9988-7711',
                'pendidikan_terakhir' => 'S2 Kebijakan Publik',
            ],
            [
                'nama' => 'Ratih Kumala, S.E.',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 4',
                'nomor_urut' => 2,
                'jenis_kelamin' => 'P',
                'foto' => null,
                'jabatan' => 'Bendahara DPC Kebasen / Pengusaha Muda',
                'basis_wilayah' => 'Kebasen & Rawalo',
                'target_suara' => 6500,
                'suara_masuk' => 4950,
                'status' => 'DCT',
                'slogan' => 'Ekonomi Kreatif Wangon dan Sekitarnya',
                'phone' => '0815-4433-2211',
                'pendidikan_terakhir' => 'S1 Manajemen Keuangan',
            ],
            [
                'nama' => 'Sukirno Hadi',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 4',
                'nomor_urut' => 3,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Ketua DPC Jatilawang',
                'basis_wilayah' => 'Jatilawang',
                'target_suara' => 6000,
                'suara_masuk' => 4410,
                'status' => 'DCT',
                'slogan' => 'Aspirasi Warga Jatilawang Terdepan',
                'phone' => '0813-8877-6611',
                'pendidikan_terakhir' => 'SMA / Sederajat',
            ],
            [
                'nama' => 'Bambang Sugito',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 4',
                'nomor_urut' => 4,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Ketua DPC Kebasen',
                'basis_wilayah' => 'Kebasen',
                'target_suara' => 5500,
                'suara_masuk' => 3890,
                'status' => 'DCT',
                'slogan' => 'Infrastruktur Jalan Desa Mulus Tanpa Lubang',
                'phone' => '0857-1234-9988',
                'pendidikan_terakhir' => 'D3 Teknik',
            ],
            [
                'nama' => 'Setiyani, S.Kep.',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 4',
                'nomor_urut' => 5,
                'jenis_kelamin' => 'P',
                'foto' => null,
                'jabatan' => 'Wakil Ketua Bidang Kesehatan DPD / Perawat',
                'basis_wilayah' => 'Rawalo & Wangon',
                'target_suara' => 5000,
                'suara_masuk' => 3620,
                'status' => 'DCT',
                'slogan' => 'Layanan Kesehatan Gratis dan Puskesmas Ramah Warga',
                'phone' => '0819-2233-4455',
                'pendidikan_terakhir' => 'S1 Keperawatan',
            ],
            [
                'nama' => 'Subagyo',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 4',
                'nomor_urut' => 6,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Ketua DPC Rawalo',
                'basis_wilayah' => 'Rawalo',
                'target_suara' => 4500,
                'suara_masuk' => 3120,
                'status' => 'DCT',
                'slogan' => 'Bersama Menjaga Tanggul Serayu dan Lahan Tani',
                'phone' => '0822-3344-5566',
                'pendidikan_terakhir' => 'SMA / Sederajat',
            ],
            [
                'nama' => 'Toni',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 4',
                'nomor_urut' => 7,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Wakil Ketua Bidang Kaderisasi & Dikpol',
                'basis_wilayah' => 'Wangon & Kebasen',
                'target_suara' => 4000,
                'suara_masuk' => 2780,
                'status' => 'DCT',
                'slogan' => 'Kader Militan Memperjuangkan Hak Rakyat',
                'phone' => '0812-7788-9900',
                'pendidikan_terakhir' => 'S1 Ilmu Politik',
            ],
            [
                'nama' => 'Sri Wahyuni',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 4',
                'nomor_urut' => 8,
                'jenis_kelamin' => 'P',
                'foto' => null,
                'jabatan' => 'Bendahara DPC Rawalo',
                'basis_wilayah' => 'Rawalo',
                'target_suara' => 3500,
                'suara_masuk' => 2240,
                'status' => 'DCT',
                'slogan' => 'Perempuan Berdaya Menuju Keluarga Bahagia',
                'phone' => '0878-3344-5511',
                'pendidikan_terakhir' => 'SMA / Sederajat',
            ],

            // DAPIL 5 (Alokasi 8 Kursi - Ajibarang, Gumelar, Pekuncen, Lumbir)
            [
                'nama' => 'H. Mufid, S.E.',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 5',
                'nomor_urut' => 1,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Ketua DPC Pekuncen / Pengusaha Agrobisnis',
                'basis_wilayah' => 'Pekuncen & Ajibarang',
                'target_suara' => 11500,
                'suara_masuk' => 10840,
                'status' => 'Caleg Terpilih',
                'slogan' => 'Modernisasi Pertanian Lereng Gunung Slamet',
                'phone' => '0813-2211-9988',
                'pendidikan_terakhir' => 'S1 Ekonomi Bisnis',
            ],
            [
                'nama' => 'Sri Rejeki, S.E.',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 5',
                'nomor_urut' => 2,
                'jenis_kelamin' => 'P',
                'foto' => null,
                'jabatan' => 'Bendahara DPC Ajibarang',
                'basis_wilayah' => 'Ajibarang & Gumelar',
                'target_suara' => 7000,
                'suara_masuk' => 5230,
                'status' => 'DCT',
                'slogan' => 'Pemberdayaan Pedagang Pasar Tradisional',
                'phone' => '0858-6677-8811',
                'pendidikan_terakhir' => 'S1 Ekonomi Akuntansi',
            ],
            [
                'nama' => 'Teguh Prabowo',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 5',
                'nomor_urut' => 3,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Ketua DPC Ajibarang',
                'basis_wilayah' => 'Ajibarang',
                'target_suara' => 6500,
                'suara_masuk' => 4710,
                'status' => 'DCT',
                'slogan' => 'Pusat Logistik dan Industri Ajibarang Tangguh',
                'phone' => '0812-4455-8822',
                'pendidikan_terakhir' => 'S1 Teknik Industri',
            ],
            [
                'nama' => 'Danang Kusworo',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 5',
                'nomor_urut' => 4,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Ketua DPC Gumelar',
                'basis_wilayah' => 'Gumelar',
                'target_suara' => 5000,
                'suara_masuk' => 3420,
                'status' => 'DCT',
                'slogan' => 'Akses Jalan Perkebunan Gumelar Lancar',
                'phone' => '0815-9988-1133',
                'pendidikan_terakhir' => 'SMA / Sederajat',
            ],
            [
                'nama' => 'Ari Widyawati, S.Pd.',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 5',
                'nomor_urut' => 5,
                'jenis_kelamin' => 'P',
                'foto' => null,
                'jabatan' => 'Wakil Ketua Bidang Pendidikan DPD',
                'basis_wilayah' => 'Lumbir & Gumelar',
                'target_suara' => 4500,
                'suara_masuk' => 3280,
                'status' => 'DCT',
                'slogan' => 'Beasiswa Kuliah untuk Anak Petani Lumbir',
                'phone' => '0821-3322-1188',
                'pendidikan_terakhir' => 'S1 Pendidikan',
            ],
            [
                'nama' => 'Rustam Effendi',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 5',
                'nomor_urut' => 6,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Ketua DPC Lumbir',
                'basis_wilayah' => 'Lumbir',
                'target_suara' => 4500,
                'suara_masuk' => 3100,
                'status' => 'DCT',
                'slogan' => 'Solusi Air Bersih dan Bencana di Daerah Perbukitan',
                'phone' => '0813-8899-0011',
                'pendidikan_terakhir' => 'SMA / Sederajat',
            ],
            [
                'nama' => 'Eko Mediantoro, S.H.',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 5',
                'nomor_urut' => 7,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Wakil Ketua Bidang Hukum & HAM DPD',
                'basis_wilayah' => 'Pekuncen',
                'target_suara' => 4000,
                'suara_masuk' => 2850,
                'status' => 'DCT',
                'slogan' => 'Bantuan Advokasi Sengketa Tanah Warga',
                'phone' => '0819-7788-9900',
                'pendidikan_terakhir' => 'S1 Ilmu Hukum',
            ],
            [
                'nama' => 'Titin Maryati',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 5',
                'nomor_urut' => 8,
                'jenis_kelamin' => 'P',
                'foto' => null,
                'jabatan' => 'Bendahara DPC Lumbir',
                'basis_wilayah' => 'Lumbir',
                'target_suara' => 3500,
                'suara_masuk' => 2180,
                'status' => 'DCT',
                'slogan' => 'Keterampilan Menjahit dan Wirausaha Perempuan Desa',
                'phone' => '0877-4455-6677',
                'pendidikan_terakhir' => 'SMA / Sederajat',
            ],

            // DAPIL 6 (Alokasi 8 Kursi - Cilongok, Karanglewas, Kedungbanteng, Purwojati)
            [
                'nama' => 'Nurokhman',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 6',
                'nomor_urut' => 1,
                'jenis_kelamin' => 'L',
                'foto' => '/storage/uploads/officer_1789628970_w0bwnrju.jpg',
                'jabatan' => 'Wakil Ketua Bidang Pemenangan Pemilu DPD',
                'basis_wilayah' => 'Cilongok & Karanglewas',
                'target_suara' => 13000,
                'suara_masuk' => 12450,
                'status' => 'Caleg Terpilih',
                'slogan' => 'Kerja Nyata, Mengakar, dan Terbukti untuk Cilongok Raya',
                'phone' => '0811-2511-1471',
                'pendidikan_terakhir' => 'S1 Ilmu Pemerintahan',
            ],
            [
                'nama' => 'Dewi Sartika, S.Pd.',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 6',
                'nomor_urut' => 2,
                'jenis_kelamin' => 'P',
                'foto' => null,
                'jabatan' => 'Bendahara DPC Karanglewas / Pendidik',
                'basis_wilayah' => 'Karanglewas & Purwojati',
                'target_suara' => 7500,
                'suara_masuk' => 5610,
                'status' => 'DCT',
                'slogan' => 'Pendidikan Inklusif dan Perlindungan Hak Perempuan',
                'phone' => '0812-3344-5566',
                'pendidikan_terakhir' => 'S1 Kependidikan',
            ],
            [
                'nama' => 'H. Mulyono',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 6',
                'nomor_urut' => 3,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Ketua DPC Cilongok / Pengusaha Gula Kelapa',
                'basis_wilayah' => 'Cilongok (20 Desa)',
                'target_suara' => 8000,
                'suara_masuk' => 6180,
                'status' => 'DCT',
                'slogan' => 'Harga Gula Semut Menguntungkan Petani Penderes',
                'phone' => '0813-4455-6677',
                'pendidikan_terakhir' => 'SMA / Sederajat',
            ],
            [
                'nama' => 'Hartono',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 6',
                'nomor_urut' => 4,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Ketua DPC Kedungbanteng',
                'basis_wilayah' => 'Kedungbanteng',
                'target_suara' => 6000,
                'suara_masuk' => 4240,
                'status' => 'DCT',
                'slogan' => 'Desa Tangguh Wisata Curug dan Pertanian Organik',
                'phone' => '0857-8899-0011',
                'pendidikan_terakhir' => 'SMA / Sederajat',
            ],
            [
                'nama' => 'Purnomo Sidi',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 6',
                'nomor_urut' => 5,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Ketua DPC Karanglewas',
                'basis_wilayah' => 'Karanglewas',
                'target_suara' => 5500,
                'suara_masuk' => 3890,
                'status' => 'DCT',
                'slogan' => 'Pengaspalan Jalan Penghubung Antar Desa',
                'phone' => '0812-6677-8899',
                'pendidikan_terakhir' => 'SMA / Sederajat',
            ],
            [
                'nama' => 'Farkhan Putri Antony',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 6',
                'nomor_urut' => 6,
                'jenis_kelamin' => 'P',
                'foto' => null,
                'jabatan' => 'Wakil Ketua Bidang Lingkungan Hidup DPD',
                'basis_wilayah' => 'Kedungbanteng & Cilongok',
                'target_suara' => 4500,
                'suara_masuk' => 3120,
                'status' => 'DCT',
                'slogan' => 'Kelestarian Hutan Slamet & Pengelolaan Sampah Mandiri',
                'phone' => '0898-1122-3344',
                'pendidikan_terakhir' => 'S1 Teknik Lingkungan',
            ],
            [
                'nama' => 'Kurniawan',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 6',
                'nomor_urut' => 7,
                'jenis_kelamin' => 'L',
                'foto' => null,
                'jabatan' => 'Ketua DPC Purwojati',
                'basis_wilayah' => 'Purwojati',
                'target_suara' => 4500,
                'suara_masuk' => 3080,
                'status' => 'DCT',
                'slogan' => 'Pelayanan Administrasi Warga Cepat dan Ramah',
                'phone' => '0813-1144-7788',
                'pendidikan_terakhir' => 'SMA / Sederajat',
            ],
            [
                'nama' => 'Indah Permata, S.Farm.',
                'tingkat' => 'DPRD Kabupaten',
                'dapil' => 'Dapil 6',
                'nomor_urut' => 8,
                'jenis_kelamin' => 'P',
                'foto' => null,
                'jabatan' => 'Bendahara DPC Kedungbanteng / Apoteker',
                'basis_wilayah' => 'Kedungbanteng',
                'target_suara' => 4000,
                'suara_masuk' => 2680,
                'status' => 'DCT',
                'slogan' => 'Apotek Desa dan Kemudahan Obat bagi Lansia',
                'phone' => '0878-9900-1122',
                'pendidikan_terakhir' => 'S1 Farmasi',
            ],
        ];

        foreach ($candidates as $c) {
            Candidate::create($c);
        }

        // =========================================================================
        // 3. QUICK COUNT TPS (Contoh Data Hasil TPS Berbagai Kecamatan & Dapil)
        // =========================================================================
        QuickCountTps::query()->delete();

        $tpsData = [
            // Dapil 1
            [
                'dapil' => 'Dapil 1',
                'kecamatan_name' => 'Purwokerto Barat',
                'desa_name' => 'Rejasari',
                'tps_number' => 'TPS 04',
                'total_dpt' => 268,
                'suara_nasdem' => 68,
                'suara_sah' => 242,
                'suara_tidak_sah' => 12,
                'saksi_name' => 'Agus Triyono',
                'saksi_phone' => '0812-3344-5501',
                'status' => 'Terverifikasi',
                'notes' => 'C1 Plano asli terbaca jelas, NasDem urutan ke-2 setelah PDI-P.',
            ],
            [
                'dapil' => 'Dapil 1',
                'kecamatan_name' => 'Purwokerto Selatan',
                'desa_name' => 'Karangpucung',
                'tps_number' => 'TPS 12',
                'total_dpt' => 280,
                'suara_nasdem' => 84,
                'suara_sah' => 258,
                'suara_tidak_sah' => 9,
                'saksi_name' => 'Bambang Irawan',
                'saksi_phone' => '0813-2233-4402',
                'status' => 'Terverifikasi',
                'notes' => 'Basis kuat pemilih Dr. Edris Santoso.',
            ],
            [
                'dapil' => 'Dapil 1',
                'kecamatan_name' => 'Patikraja',
                'desa_name' => 'Sidabowa',
                'tps_number' => 'TPS 07',
                'total_dpt' => 255,
                'suara_nasdem' => 52,
                'suara_sah' => 230,
                'suara_tidak_sah' => 15,
                'saksi_name' => 'Wahyono',
                'saksi_phone' => '0857-1122-3303',
                'status' => 'Terverifikasi',
                'notes' => 'Formulir C1 telah ditandatangani semua saksi parpol.',
            ],
            [
                'dapil' => 'Dapil 1',
                'kecamatan_name' => 'Purwokerto Timur',
                'desa_name' => 'Arcawinangun',
                'tps_number' => 'TPS 02',
                'total_dpt' => 275,
                'suara_nasdem' => 45,
                'suara_sah' => 240,
                'suara_tidak_sah' => 8,
                'saksi_name' => 'Dedi Santoso',
                'saksi_phone' => '0819-3344-5504',
                'status' => 'Menunggu Verifikasi',
                'notes' => 'Foto C1 baru diupload via WhatsApp saksi TPS.',
            ],

            // Dapil 2
            [
                'dapil' => 'Dapil 2',
                'kecamatan_name' => 'Sokaraja',
                'desa_name' => 'Sokaraja Kulon',
                'tps_number' => 'TPS 05',
                'total_dpt' => 290,
                'suara_nasdem' => 92,
                'suara_sah' => 265,
                'suara_tidak_sah' => 11,
                'saksi_name' => 'Suripno',
                'saksi_phone' => '0812-7788-9905',
                'status' => 'Terverifikasi',
                'notes' => 'Dominasi H. Muhlasin sangat signifikan di TPS ini.',
            ],
            [
                'dapil' => 'Dapil 2',
                'kecamatan_name' => 'Kembaran',
                'desa_name' => 'Dukuhwaluh',
                'tps_number' => 'TPS 09',
                'total_dpt' => 260,
                'suara_nasdem' => 58,
                'suara_sah' => 235,
                'suara_tidak_sah' => 14,
                'saksi_name' => 'Rizki Fauzi',
                'saksi_phone' => '0858-1122-3306',
                'status' => 'Terverifikasi',
                'notes' => 'Pemilih pemula mahasiswa UMP banyak mencoblos NasDem.',
            ],
            [
                'dapil' => 'Dapil 2',
                'kecamatan_name' => 'Sumbang',
                'desa_name' => 'Banteran',
                'tps_number' => 'TPS 03',
                'total_dpt' => 272,
                'suara_nasdem' => 64,
                'suara_sah' => 248,
                'suara_tidak_sah' => 7,
                'saksi_name' => 'Slamet Subur',
                'saksi_phone' => '0813-4455-6607',
                'status' => 'Terverifikasi',
                'notes' => 'Sinkron dengan rekapitulasi PPS desa setempat.',
            ],
            [
                'dapil' => 'Dapil 2',
                'kecamatan_name' => 'Baturraden',
                'desa_name' => 'Rempoah',
                'tps_number' => 'TPS 08',
                'total_dpt' => 245,
                'suara_nasdem' => 48,
                'suara_sah' => 220,
                'suara_tidak_sah' => 10,
                'saksi_name' => 'Joko Prayitno',
                'saksi_phone' => '0818-5566-7708',
                'status' => 'Menunggu Verifikasi',
                'notes' => 'Perhitungan suara selesai pukul 17:30 WIB.',
            ],

            // Dapil 3
            [
                'dapil' => 'Dapil 3',
                'kecamatan_name' => 'Kemranjen',
                'desa_name' => 'Kecila',
                'tps_number' => 'TPS 01',
                'total_dpt' => 285,
                'suara_nasdem' => 88,
                'suara_sah' => 260,
                'suara_tidak_sah' => 12,
                'saksi_name' => 'Tohirin',
                'saksi_phone' => '0812-9900-1109',
                'status' => 'Terverifikasi',
                'notes' => 'Basis Drs. Supardi, M.Pd.',
            ],
            [
                'dapil' => 'Dapil 3',
                'kecamatan_name' => 'Sumpiuh',
                'desa_name' => 'Kebokura',
                'tps_number' => 'TPS 06',
                'total_dpt' => 270,
                'suara_nasdem' => 76,
                'suara_sah' => 245,
                'suara_tidak_sah' => 13,
                'saksi_name' => 'Darsono',
                'saksi_phone' => '0856-7788-9910',
                'status' => 'Terverifikasi',
                'notes' => 'Hasil mantap, saksi partai lain menerima berita acara.',
            ],
            [
                'dapil' => 'Dapil 3',
                'kecamatan_name' => 'Tambak',
                'desa_name' => 'Kamulyan',
                'tps_number' => 'TPS 04',
                'total_dpt' => 265,
                'suara_nasdem' => 61,
                'suara_sah' => 238,
                'suara_tidak_sah' => 9,
                'saksi_name' => 'Munawar',
                'saksi_phone' => '0813-2211-4411',
                'status' => 'Terverifikasi',
                'notes' => 'C1 terunggah sempurna.',
            ],

            // Dapil 4
            [
                'dapil' => 'Dapil 4',
                'kecamatan_name' => 'Wangon',
                'desa_name' => 'Klapagading',
                'tps_number' => 'TPS 10',
                'total_dpt' => 295,
                'suara_nasdem' => 95,
                'suara_sah' => 270,
                'suara_tidak_sah' => 8,
                'saksi_name' => 'Sodikun',
                'saksi_phone' => '0812-3322-1112',
                'status' => 'Terverifikasi',
                'notes' => 'Basis kyai dan santri Drs. H. Mahrus.',
            ],
            [
                'dapil' => 'Dapil 4',
                'kecamatan_name' => 'Jatilawang',
                'desa_name' => 'Tinggarjaya',
                'tps_number' => 'TPS 05',
                'total_dpt' => 260,
                'suara_nasdem' => 54,
                'suara_sah' => 232,
                'suara_tidak_sah' => 14,
                'saksi_name' => 'Triyono',
                'saksi_phone' => '0819-4455-6613',
                'status' => 'Terverifikasi',
                'notes' => 'Suara partai aman terkendali.',
            ],

            // Dapil 5
            [
                'dapil' => 'Dapil 5',
                'kecamatan_name' => 'Pekuncen',
                'desa_name' => 'Banjaranyar',
                'tps_number' => 'TPS 02',
                'total_dpt' => 280,
                'suara_nasdem' => 90,
                'suara_sah' => 256,
                'suara_tidak_sah' => 11,
                'saksi_name' => 'Kuswadi',
                'saksi_phone' => '0857-1133-5514',
                'status' => 'Terverifikasi',
                'notes' => 'Suara H. Mufid unggul telak di TPS ini.',
            ],
            [
                'dapil' => 'Dapil 5',
                'kecamatan_name' => 'Ajibarang',
                'desa_name' => 'Ajibarang Kulon',
                'tps_number' => 'TPS 08',
                'total_dpt' => 285,
                'suara_nasdem' => 78,
                'suara_sah' => 262,
                'suara_tidak_sah' => 10,
                'saksi_name' => 'Hadi Suwito',
                'saksi_phone' => '0813-7788-9915',
                'status' => 'Terverifikasi',
                'notes' => 'Saksi telah melampirkan salinan C1 plano berstempel KPPS.',
            ],

            // Dapil 6
            [
                'dapil' => 'Dapil 6',
                'kecamatan_name' => 'Cilongok',
                'desa_name' => 'Pernasidi',
                'tps_number' => 'TPS 11',
                'total_dpt' => 298,
                'suara_nasdem' => 112,
                'suara_sah' => 275,
                'suara_tidak_sah' => 9,
                'saksi_name' => 'Kusnadi',
                'saksi_phone' => '0811-2233-4416',
                'status' => 'Terverifikasi',
                'notes' => 'Lumbung suara Nurokhman (Bapilu DPD NasDem). NasDem nomor 1 di TPS ini!',
            ],
            [
                'dapil' => 'Dapil 6',
                'kecamatan_name' => 'Karanglewas',
                'desa_name' => 'Karanglewas Kidul',
                'tps_number' => 'TPS 04',
                'total_dpt' => 270,
                'suara_nasdem' => 66,
                'suara_sah' => 244,
                'suara_tidak_sah' => 12,
                'saksi_name' => 'Nanang Kosim',
                'saksi_phone' => '0812-4455-6617',
                'status' => 'Terverifikasi',
                'notes' => 'Verifikasi pleno tingkat TPS selesai tertib.',
            ],
            [
                'dapil' => 'Dapil 6',
                'kecamatan_name' => 'Kedungbanteng',
                'desa_name' => 'Beji',
                'tps_number' => 'TPS 03',
                'total_dpt' => 265,
                'suara_nasdem' => 59,
                'suara_sah' => 236,
                'suara_tidak_sah' => 15,
                'saksi_name' => 'Eko Prasetyo',
                'saksi_phone' => '0858-9900-1118',
                'status' => 'Menunggu Verifikasi',
                'notes' => 'Memeriksa lembar C1 plano halaman 2.',
            ],
        ];

        foreach ($tpsData as $tps) {
            QuickCountTps::create($tps);
        }
    }
}
